/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all tournaments */
        get: operations["listTournaments"];
        put?: never;
        /** Create a tournament */
        post: operations["createTournament"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tournament by ID */
        get: operations["getTournamentByID"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tournament by slug */
        get: operations["getTournamentBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's leagues */
        get: operations["listLeagues"];
        put?: never;
        /** Create a league */
        post: operations["createLeague"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a league via invite code */
        post: operations["joinLeague"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get league with members */
        get: operations["getLeague"];
        put?: never;
        post?: never;
        /** Delete a league */
        delete: operations["deleteLeague"];
        options?: never;
        head?: never;
        /** Update league name */
        patch: operations["updateLeagueName"];
        trace?: never;
    };
    "/leagues/{id}/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate league invite code */
        post: operations["regenerateLeagueCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member from a league */
        delete: operations["removeLeagueMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournament_id}/players/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search players in a tournament */
        get: operations["searchPlayers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/player-handicaps/{player_id}/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get player handicap by category */
        get: operations["getPlayerHandicap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team-handicaps/{team_id}/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get team handicap by category */
        get: operations["getTeamHandicap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/predictions/players/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert player tournament prediction */
        put: operations["upsertPlayerPrediction"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/predictions/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my player predictions for a tournament */
        get: operations["listMyPlayerPredictions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/predictions/teams/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert team tournament prediction */
        put: operations["upsertTeamPrediction"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournaments/{tournamentId}/predictions/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my team predictions for a tournament */
        get: operations["listMyTeamPredictions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{leagueId}/predictions/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List league player predictions (after lock) */
        get: operations["listLeaguePlayerPredictions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{leagueId}/predictions/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List league team predictions (after lock) */
        get: operations["listLeagueTeamPredictions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve OpenAPI spec as JSON */
        get: operations["getOpenAPISpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Swagger UI */
        get: operations["getDocs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "error": "not found"
         *     }
         */
        ErrorResponse: {
            error: string;
        };
        /**
         * @example {
         *       "id": "550e8400-e29b-41d4-a716-446655440000",
         *       "slug": "world-cup-2026",
         *       "name": "FIFA World Cup 2026",
         *       "status": "upcoming",
         *       "starts_at": "2026-06-11T00:00:00Z",
         *       "ends_at": "2026-07-19T00:00:00Z",
         *       "created_at": "2025-01-01T00:00:00Z",
         *       "updated_at": "2025-01-01T00:00:00Z"
         *     }
         */
        Tournament: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            /** @enum {string} */
            status: "upcoming" | "in_progress" | "concluded";
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @example {
         *       "id": "550e8400-e29b-41d4-a716-446655440001",
         *       "tournament_id": "550e8400-e29b-41d4-a716-446655440000",
         *       "owner_id": "550e8400-e29b-41d4-a716-446655440002",
         *       "name": "My Prediction League",
         *       "code": "ABCD1234",
         *       "created_at": "2025-01-01T00:00:00Z",
         *       "updated_at": "2025-01-01T00:00:00Z"
         *     }
         */
        League: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tournament_id: string;
            /** Format: uuid */
            owner_id: string;
            name: string;
            code: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @example {
         *       "user_id": "550e8400-e29b-41d4-a716-446655440002",
         *       "role": "owner",
         *       "joined_at": "2025-01-01T00:00:00Z"
         *     }
         */
        LeagueMember: {
            /** Format: uuid */
            user_id: string;
            /** @enum {string} */
            role: "owner" | "member";
            /** Format: date-time */
            joined_at: string;
        };
        /**
         * @example {
         *       "id": "550e8400-e29b-41d4-a716-446655440001",
         *       "tournament_id": "550e8400-e29b-41d4-a716-446655440000",
         *       "owner_id": "550e8400-e29b-41d4-a716-446655440002",
         *       "name": "My Prediction League",
         *       "code": "ABCD1234",
         *       "created_at": "2025-01-01T00:00:00Z",
         *       "updated_at": "2025-01-01T00:00:00Z",
         *       "members": [
         *         {
         *           "user_id": "550e8400-e29b-41d4-a716-446655440002",
         *           "role": "owner",
         *           "joined_at": "2025-01-01T00:00:00Z"
         *         }
         *       ]
         *     }
         */
        LeagueDetail: components["schemas"]["League"] & {
            members: components["schemas"]["LeagueMember"][];
        };
        /**
         * @example {
         *       "id": "550e8400-e29b-41d4-a716-446655440001",
         *       "tournament_id": "550e8400-e29b-41d4-a716-446655440000",
         *       "owner_id": "550e8400-e29b-41d4-a716-446655440002",
         *       "name": "My Prediction League",
         *       "code": "ABCD1234",
         *       "created_at": "2025-01-01T00:00:00Z",
         *       "updated_at": "2025-01-01T00:00:00Z",
         *       "member_count": 3
         *     }
         */
        LeagueListItem: components["schemas"]["League"] & {
            /** @description Total number of members in this league. */
            member_count: number;
        };
        /**
         * @example {
         *       "id": "550e8400-e29b-41d4-a716-446655440002",
         *       "email": "user@example.com",
         *       "display_name": "John Doe",
         *       "status": "active",
         *       "created_at": "2025-01-01T00:00:00Z",
         *       "updated_at": "2025-01-01T00:00:00Z"
         *     }
         */
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** @enum {string} */
            status: "active" | "suspended";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /**
         * @example {
         *       "id": "550e8400-e29b-41d4-a716-446655440003",
         *       "name": "Kylian Mbappe",
         *       "team_name": "France",
         *       "team_logo": "https://example.com/france.png",
         *       "handicaps": {
         *         "group_top_scorer": 5,
         *         "total_top_scorer": 10
         *       }
         *     }
         */
        Player: {
            /** Format: uuid */
            id: string;
            name: string;
            team_name: string;
            team_logo: string;
            handicaps: {
                [key: string]: number;
            };
        };
        /**
         * @example {
         *       "points": 5
         *     }
         */
        PlayerHandicap: {
            points: number;
        };
        /**
         * @example {
         *       "points": 3
         *     }
         */
        TeamHandicap: {
            points: number;
        };
        /**
         * @example group_top_scorer
         * @enum {string}
         */
        PlayerHandicapCategory: "group_top_scorer" | "total_top_scorer";
        /**
         * @example winner
         * @enum {string}
         */
        TeamHandicapCategory: "group_winner" | "playoff" | "semifinalist" | "winner";
        /**
         * @example {
         *       "tournaments": [
         *         {
         *           "id": "550e8400-e29b-41d4-a716-446655440000",
         *           "slug": "world-cup-2026",
         *           "name": "FIFA World Cup 2026",
         *           "status": "upcoming",
         *           "starts_at": "2026-06-11T00:00:00Z",
         *           "ends_at": "2026-07-19T00:00:00Z",
         *           "created_at": "2025-01-01T00:00:00Z",
         *           "updated_at": "2025-01-01T00:00:00Z"
         *         }
         *       ]
         *     }
         */
        TournamentListResponse: {
            tournaments: components["schemas"]["Tournament"][];
        };
        /**
         * @example {
         *       "leagues": [
         *         {
         *           "id": "550e8400-e29b-41d4-a716-446655440001",
         *           "tournament_id": "550e8400-e29b-41d4-a716-446655440000",
         *           "owner_id": "550e8400-e29b-41d4-a716-446655440002",
         *           "name": "My Prediction League",
         *           "code": "ABCD1234",
         *           "created_at": "2025-01-01T00:00:00Z",
         *           "updated_at": "2025-01-01T00:00:00Z",
         *           "member_count": 3
         *         }
         *       ]
         *     }
         */
        LeagueListResponse: {
            leagues: components["schemas"]["LeagueListItem"][];
        };
        /**
         * @example {
         *       "players": [
         *         {
         *           "id": "550e8400-e29b-41d4-a716-446655440003",
         *           "name": "Kylian Mbappe",
         *           "team_name": "France",
         *           "team_logo": "https://example.com/france.png",
         *           "handicaps": {
         *             "group_top_scorer": 5,
         *             "total_top_scorer": 10
         *           }
         *         }
         *       ]
         *     }
         */
        PlayerListResponse: {
            players: components["schemas"]["Player"][];
        };
        /**
         * @example {
         *       "player_id": "550e8400-e29b-41d4-a716-446655440003"
         *     }
         */
        UpsertPlayerPredictionRequest: {
            /** Format: uuid */
            player_id: string;
        };
        /**
         * @example {
         *       "team_id": "550e8400-e29b-41d4-a716-446655440004"
         *     }
         */
        UpsertTeamPredictionRequest: {
            /** Format: uuid */
            team_id: string;
        };
        /**
         * @example {
         *       "id": "550e8400-e29b-41d4-a716-446655440010",
         *       "tournament_id": "550e8400-e29b-41d4-a716-446655440000",
         *       "category": "group_top_scorer",
         *       "player_id": "550e8400-e29b-41d4-a716-446655440003",
         *       "player_name": "Lionel Messi",
         *       "points": null
         *     }
         */
        PlayerPredictionResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tournament_id: string;
            category: components["schemas"]["PlayerHandicapCategory"];
            /** Format: uuid */
            player_id: string;
            player_name: string;
            points?: number | null;
        };
        /**
         * @example {
         *       "id": "550e8400-e29b-41d4-a716-446655440011",
         *       "tournament_id": "550e8400-e29b-41d4-a716-446655440000",
         *       "category": "winner",
         *       "team_id": "550e8400-e29b-41d4-a716-446655440004",
         *       "team_name": "Argentina",
         *       "points": null
         *     }
         */
        TeamPredictionResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tournament_id: string;
            category: components["schemas"]["TeamHandicapCategory"];
            /** Format: uuid */
            team_id: string;
            team_name: string;
            points?: number | null;
        };
        /**
         * @example {
         *       "category": "group_top_scorer",
         *       "player_id": "550e8400-e29b-41d4-a716-446655440003",
         *       "player_name": "Lionel Messi",
         *       "points": null
         *     }
         */
        PlayerPredictionView: {
            category: components["schemas"]["PlayerHandicapCategory"];
            /** Format: uuid */
            player_id?: string | null;
            player_name?: string | null;
            points?: number | null;
        };
        /**
         * @example {
         *       "category": "winner",
         *       "team_id": "550e8400-e29b-41d4-a716-446655440004",
         *       "team_name": "Argentina",
         *       "points": null
         *     }
         */
        TeamPredictionView: {
            category: components["schemas"]["TeamHandicapCategory"];
            /** Format: uuid */
            team_id?: string | null;
            team_name?: string | null;
            points?: number | null;
        };
        /**
         * @example {
         *       "user_id": "550e8400-e29b-41d4-a716-446655440002",
         *       "display_name": "alice",
         *       "player_id": "550e8400-e29b-41d4-a716-446655440003",
         *       "player_name": "Lionel Messi",
         *       "points": 5
         *     }
         */
        LeagueMemberPlayerPick: {
            /** Format: uuid */
            user_id: string;
            display_name: string;
            /** Format: uuid */
            player_id?: string | null;
            player_name?: string | null;
            points?: number | null;
        };
        /**
         * @example {
         *       "user_id": "550e8400-e29b-41d4-a716-446655440002",
         *       "display_name": "alice",
         *       "team_id": "550e8400-e29b-41d4-a716-446655440004",
         *       "team_name": "Argentina",
         *       "points": null
         *     }
         */
        LeagueMemberTeamPick: {
            /** Format: uuid */
            user_id: string;
            display_name: string;
            /** Format: uuid */
            team_id?: string | null;
            team_name?: string | null;
            points?: number | null;
        };
        /**
         * @example {
         *       "category": "group_top_scorer",
         *       "predictions": [
         *         {
         *           "user_id": "550e8400-e29b-41d4-a716-446655440002",
         *           "display_name": "me",
         *           "player_id": "550e8400-e29b-41d4-a716-446655440003",
         *           "player_name": "Messi",
         *           "points": 5
         *         }
         *       ]
         *     }
         */
        LeaguePlayerCategoryView: {
            category: components["schemas"]["PlayerHandicapCategory"];
            predictions: components["schemas"]["LeagueMemberPlayerPick"][];
        };
        /**
         * @example {
         *       "category": "winner",
         *       "predictions": [
         *         {
         *           "user_id": "550e8400-e29b-41d4-a716-446655440002",
         *           "display_name": "me",
         *           "team_id": "550e8400-e29b-41d4-a716-446655440004",
         *           "team_name": "Argentina",
         *           "points": null
         *         }
         *       ]
         *     }
         */
        LeagueTeamCategoryView: {
            category: components["schemas"]["TeamHandicapCategory"];
            predictions: components["schemas"]["LeagueMemberTeamPick"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": {
                        status: string;
                    };
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is ready to serve traffic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ready"
                     *     }
                     */
                    "application/json": {
                        status: string;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                        reason: string;
                    };
                };
            };
        };
    };
    listTournaments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tournaments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentListResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createTournament: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "slug": "world-cup-2026",
                 *       "name": "FIFA World Cup 2026",
                 *       "starts_at": "2026-06-11T00:00:00Z",
                 *       "ends_at": "2026-07-19T00:00:00Z"
                 *     }
                 */
                "application/json": {
                    slug: string;
                    name: string;
                    /** Format: date-time */
                    starts_at: string;
                    /** Format: date-time */
                    ends_at: string;
                };
            };
        };
        responses: {
            /** @description Tournament created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tournament"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Tournament with slug already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTournamentByID: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tournament found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tournament"];
                };
            };
            /** @description Invalid UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Tournament not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTournamentBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tournament found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tournament"];
                };
            };
            /** @description Tournament not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listLeagues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User's leagues */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createLeague: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "tournament_id": "550e8400-e29b-41d4-a716-446655440000",
                 *       "name": "My Prediction League"
                 *     }
                 */
                "application/json": {
                    /** Format: uuid */
                    tournament_id: string;
                    name: string;
                };
            };
        };
        responses: {
            /** @description League created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["League"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Tournament not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    joinLeague: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "code": "ABCD1234"
                 *     }
                 */
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            /** @description Joined league */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["League"];
                };
            };
            /** @description Invalid or missing code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description League not found for code */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Already a member */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLeague: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description League with members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueDetail"];
                };
            };
            /** @description Invalid UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not a member of this league */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description League not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteLeague: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description League deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not the league owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description League not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateLeagueName: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Updated League Name"
                 *     }
                 */
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description League updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["League"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not the league owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description League not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    regenerateLeagueCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description League with new invite code */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["League"];
                };
            };
            /** @description Invalid UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not the league owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description League not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removeLeagueMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not the league owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description League or member not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    searchPlayers: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path: {
                tournament_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching players */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerListResponse"];
                };
            };
            /** @description Invalid tournament ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Tournament not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPlayerHandicap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
                category: components["schemas"]["PlayerHandicapCategory"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Player handicap */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerHandicap"];
                };
            };
            /** @description Invalid player ID or category */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Handicap not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTeamHandicap: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
                category: components["schemas"]["TeamHandicapCategory"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team handicap */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamHandicap"];
                };
            };
            /** @description Invalid team ID or category */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Handicap not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upsertPlayerPrediction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: string;
                category: components["schemas"]["PlayerHandicapCategory"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertPlayerPredictionRequest"];
            };
        };
        responses: {
            /** @description Player prediction saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerPredictionResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Predictions locked */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Player not found in this tournament */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listMyPlayerPredictions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Player predictions for all categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerPredictionView"][];
                };
            };
            /** @description Invalid tournament ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upsertTeamPrediction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: string;
                category: components["schemas"]["TeamHandicapCategory"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertTeamPredictionRequest"];
            };
        };
        responses: {
            /** @description Team prediction saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamPredictionResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Predictions locked */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Team not found in this tournament */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listMyTeamPredictions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team predictions for all categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamPredictionView"][];
                };
            };
            /** @description Invalid tournament ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listLeaguePlayerPredictions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Player predictions for all categories grouped by league member */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaguePlayerCategoryView"][];
                };
            };
            /** @description Invalid league ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not a member of the league, or lock time has not passed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listLeagueTeamPredictions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team predictions for all categories grouped by league member */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueTeamCategoryView"][];
                };
            };
            /** @description Invalid league ID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not a member of the league, or lock time has not passed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOpenAPISpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI spec as JSON */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    getDocs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Swagger UI HTML page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
}
